version: "3.3"

volumes:
  gems:
  yarn-cache:

services:
  db:
    image: postgres:9.6
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: 'lnfeiurlakj3'
      POSTGRES_USER: 'lumiar'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "bundle exec hanami server --host 0.0.0.0 -p 2300"
    volumes:
      - .:/app
      - ./containers/bundle_install:/app/vendor/bundle
      - ./containers/bundle:/app/.bundle
      - ./containers/node_modules:/app/node_modules
      - gems:/usr/local/bundle
      - yarn-cache:/root/.yarn-cache

    ports:
      - 2300:2300
    depends_on:
      - db
    links:
      - db
